/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.JFrame;

/**
 *
 * @author Lucas
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        this.setVisible(true);
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_principal = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuArquivo = new javax.swing.JMenu();
        mniPessoaEmpresa = new javax.swing.JMenuItem();
        mniCreditosDebitos = new javax.swing.JMenuItem();
        mnuSair = new javax.swing.JMenu();
        mniSair = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout pnl_principalLayout = new javax.swing.GroupLayout(pnl_principal);
        pnl_principal.setLayout(pnl_principalLayout);
        pnl_principalLayout.setHorizontalGroup(
            pnl_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        pnl_principalLayout.setVerticalGroup(
            pnl_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        mnuArquivo.setText("Arquivo");

        mniPessoaEmpresa.setText("Pessoa/Empresa");
        mniPessoaEmpresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniPessoaEmpresaActionPerformed(evt);
            }
        });
        mnuArquivo.add(mniPessoaEmpresa);

        mniCreditosDebitos.setText("Créditos/Débitos");
        mniCreditosDebitos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniCreditosDebitosActionPerformed(evt);
            }
        });
        mnuArquivo.add(mniCreditosDebitos);

        jMenuBar1.add(mnuArquivo);

        mnuSair.setText("Sair");

        mniSair.setText("Sair");
        mniSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniSairActionPerformed(evt);
            }
        });
        mnuSair.add(mniSair);

        jMenuBar1.add(mnuSair);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_principal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_principal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mniSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniSairActionPerformed
        this.dispose();
    }//GEN-LAST:event_mniSairActionPerformed

    private void mniPessoaEmpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniPessoaEmpresaActionPerformed
        PessoaEmpresaView pessoaEmpresa = new PessoaEmpresaView();
        pnl_principal.removeAll();
        pnl_principal.add(pessoaEmpresa);
        pnl_principal.updateUI();
    }//GEN-LAST:event_mniPessoaEmpresaActionPerformed

    private void mniCreditosDebitosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniCreditosDebitosActionPerformed
        CreditoDebitoView creditoDebito = new CreditoDebitoView();
        pnl_principal.removeAll();
        pnl_principal.add(creditoDebito);
        pnl_principal.updateUI();
    }//GEN-LAST:event_mniCreditosDebitosActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem mniCreditosDebitos;
    private javax.swing.JMenuItem mniPessoaEmpresa;
    private javax.swing.JMenuItem mniSair;
    private javax.swing.JMenu mnuArquivo;
    private javax.swing.JMenu mnuSair;
    private javax.swing.JPanel pnl_principal;
    // End of variables declaration//GEN-END:variables
}
